### ISSUE TITLE
CONVERTING TO EXE USING PYINSTALLER HAS ERROR(Minecraft)

### ISSUE THREAD

**Issue by happyleibniz** [happyleibniz/Python-Operating-System#11]
project issue here [CONVERTING TO EXE USING PYINSTALLER HAS ERROR #1035](https://githubfast.com/pyglet/pyglet/issues/1035)

**Comment by shenjackyuanjie** [comment]
草，麻烦您把 githubfast.com 改成 github .com

**Comment by happyleibniz** [comment]
> 草，麻烦您把 githubfast.com 改成 github .com

https://github.com/pyglet/pyglet/issues/1035

**Comment by happyleibniz** [comment]
测试性minecraft转换exe成功：https://github.com/happyleibniz/Minecraft_python_Edition/releases/tag/latest
